import { QuestionType } from '../../../Question';
import { TagType } from '../../../Tag';

export interface UserType {
  id: number;
  name: string;
  password: string;
  email: string;
  emailVerify: boolean;
  type: 'company' | 'user';
  description: string;
  avatar: string;
  followers: number;
  likes: number;
  dislikes: number;
  location: string;
  birthday: string;
  summary: string;
  sessions: any[];
  roles: any[];
  banned: any;
  userInfo: any;
  tags: TagType[];
  followingTags: any[];
  followingUsers: any[];
  ignoringTags: any[];
  questions: any[];
  blocks: any[];
  favouriteQuestions: QuestionType[];
  favouriteTestQuestions: any[];
  favouriteBlocks: any[];
  favouriteTestBlocks: any[];
  favouriteUsers: any[];
  favouriteCompanies: any[];
  favouriteTags: any[];
  interviewes: any[];
  notifications: any[];
  settings: any[];
  posts: any[];
  achievements: any[];
  connection: any;
  createdAt: Date;
  updatedAt: Date;
}
